version: '3'
services:
  flask:
    build: 
      context: .
      dockerfile: Docker_python
    container_name: flask_container
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "5000:5000"
  vue:
    build:
      context: .
      dockerfile: Docker_vue
    image: vue_img
    container_name: vue_container
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - "9090:9090"
